import { MdlJeddahInputxAllprm } from "../model/mdlJeddahMainpr";

// Treatment function params
export function FncJeddahAllpnrrMainpr(params: MdlJeddahInputxAllprm) {
  return {
    chssmr: params.chssmr || "",
    clssfl_pnrdtl: params.clssfl_pnrdtl || "",
    airlfl_pnrdtl: params.airlfl_pnrdtl || "",
    datefl_pnrdtl: params.datefl_pnrdtl || "",
    pnrcde_pnrdtl: params.pnrcde_pnrdtl || "",
    pnrclk_pnrdtl: params.pnrclk_pnrdtl || "",
    flnbfl_pnrdtl: params.flnbfl_pnrdtl || "",
    routfl_pnrdtl: params.routfl_pnrdtl || "",
    agtnme_pnrdtl: params.agtnme_pnrdtl || "",
    srtspl_pnrdtl: params.srtspl_pnrdtl || "",
    srtcxl_pnrdtl: params.srtcxl_pnrdtl || "",
    pagenw_pnrdtl: Number(params.pagenw_pnrdtl) || 1,
    limitp_pnrdtl: Number(params.limitp_pnrdtl) || 15,
    airlfl_pnrsmr: params.airlfl_pnrsmr || "",
    flnbfl_pnrsmr: params.flnbfl_pnrsmr || "",
    routfl_pnrsmr: params.routfl_pnrsmr || "",
    datefl_pnrsmr: params.datefl_pnrsmr || "",
    pnrcde_pnrsmr: params.pnrcde_pnrsmr || "",
    pnrclk_pnrsmr: params.pnrclk_pnrsmr || "",
    agtnme_pnrsmr: params.agtnme_pnrsmr || "",
    psdate_pnrsmr: params.psdate_pnrsmr || "",
    srtspl_pnrsmr: params.srtspl_pnrsmr || "",
    srtcxl_pnrsmr: params.srtcxl_pnrsmr || "",
    pagenw_pnrsmr: Number(params.pagenw_pnrsmr) || 1,
    limitp_pnrsmr: Number(params.limitp_pnrsmr) || 15,
    airlfl_flnsmr: params.airlfl_flnsmr || "",
    datefl_flnsmr: params.datefl_flnsmr || "",
    flnbfl_flnsmr: params.flnbfl_flnsmr || "",
    routfl_flnsmr: params.routfl_flnsmr || "",
    psdate_flnsmr: params.psdate_flnsmr || "",
    srtspl_flnsmr: params.srtspl_flnsmr || "",
    srtcxl_flnsmr: params.srtcxl_flnsmr || "",
    pagenw_flnsmr: Number(params.pagenw_flnsmr) || 1,
    limitp_flnsmr: Number(params.limitp_flnsmr) || 15,
    airlfl_agtnme: params.airlfl_agtnme || "",
    agtnme_agtnme: params.agtnme_agtnme || "",
    srtnul_agtnme: params.srtnul_agtnme || "",
    pagenw_agtnme: Number(params.pagenw_agtnme) || 1,
    limitp_agtnme: Number(params.limitp_agtnme) || 15,
  } as MdlJeddahInputxAllprm;
}
